In [ ]:
import numpy as np

In [ ]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.array((4,2))

array([4, 2])

In [ ]:
np.full((2,2),2,dtype=int)

array([[2, 2],
       [2, 2]])

In [ ]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
new_list = [1,2,3,4]
np.array(new_list)

array([1, 2, 3, 4])

In [ ]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.random.random(30)
a

array([0.65283477, 0.35381868, 0.13507961, 0.88690145, 0.84748254,
       0.89248049, 0.02971764, 0.13114136, 0.98938981, 0.49300461,
       0.92723648, 0.67115247, 0.49138521, 0.12705509, 0.83783328,
       0.3142989 , 0.51951575, 0.16916677, 0.10006222, 0.38266381,
       0.74677611, 0.44379341, 0.05737   , 0.76274851, 0.99630997,
       0.01229574, 0.51138704, 0.62364355, 0.62288037, 0.20778634])

In [ ]:
a.mean

<function ndarray.mean>

In [ ]:
a=np.random.randint(100,size=(10,10))
a

array([[58, 68, 95, 57, 18, 46, 80, 28,  8,  7],
       [20, 39, 68,  0, 54, 92, 74, 73, 99, 38],
       [38, 75, 21,  2, 81, 94, 58, 40, 54, 46],
       [60, 34, 74,  4, 21, 28, 60, 19, 92,  4],
       [ 8, 91, 72, 79, 37, 59, 71, 33, 41,  7],
       [36, 70, 42, 17, 22,  2, 28, 27, 59, 26],
       [38, 11, 52, 36, 76, 22, 52, 55, 83, 22],
       [55, 98, 18, 57, 44,  5, 21, 88, 19, 76],
       [98,  4, 28, 29, 32,  6, 15, 76,  2, 65],
       [59, 55, 21,  8, 31, 47, 71, 10, 90, 23]])

In [ ]:
a.max()

np.int64(99)

In [ ]:
a.min()

np.int64(0)

In [ ]:
a = np.zeros((10))
a[4]=4
a

array([0., 0., 0., 0., 4., 0., 0., 0., 0., 0.])

In [ ]:
a= np.array([1,2,0,0,4,0])
r= np.flip(a)
print(r)

[0 4 0 0 2 1]


In [42]:
a = np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
c = np.zeros((8,8),dtype=int)
c[1::2, ::2]=1
c[::2, 1::2]=1
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
